/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContactInquiriesRouteImport } from './routes/admin.contact-inquiries'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminTrialRequestsRouteImport } from './routes/admin.trial-requests'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherLogsRouteImport } from './routes/teacher.logs'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherScheduleRouteImport } from './routes/teacher.schedule'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactInquiriesRoute = AdminContactInquiriesRouteImport.update({
  id: '/contact-inquiries',
  path: '/contact-inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrialRequestsRoute = AdminTrialRequestsRouteImport.update({
  id: '/trial-requests',
  path: '/trial-requests',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLogsRoute = TeacherLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherScheduleRoute = TeacherScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/contact-inquiries': typeof AdminContactInquiriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/trial-requests': typeof AdminTrialRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/logs': typeof TeacherLogsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/contact-inquiries': typeof AdminContactInquiriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/trial-requests': typeof AdminTrialRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/logs': typeof TeacherLogsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/contact-inquiries': typeof AdminContactInquiriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/trial-requests': typeof AdminTrialRequestsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/logs': typeof TeacherLogsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/contact-inquiries'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/trial-requests'
    | '/student/profile'
    | '/teacher/dashboard'
    | '/teacher/logs'
    | '/teacher/profile'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/contact-inquiries'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/trial-requests'
    | '/student/profile'
    | '/teacher/dashboard'
    | '/teacher/logs'
    | '/teacher/profile'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/contact-inquiries'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/trial-requests'
    | '/student/profile'
    | '/teacher/dashboard'
    | '/teacher/logs'
    | '/teacher/profile'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-inquiries': {
      id: '/admin/contact-inquiries'
      path: '/contact-inquiries'
      fullPath: '/admin/contact-inquiries'
      preLoaderRoute: typeof AdminContactInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trial-requests': {
      id: '/admin/trial-requests'
      path: '/trial-requests'
      fullPath: '/admin/trial-requests'
      preLoaderRoute: typeof AdminTrialRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/logs': {
      id: '/teacher/logs'
      path: '/logs'
      fullPath: '/teacher/logs'
      preLoaderRoute: typeof TeacherLogsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/schedule': {
      id: '/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof TeacherScheduleRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContactInquiriesRoute: typeof AdminContactInquiriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTrialRequestsRoute: typeof AdminTrialRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactInquiriesRoute: AdminContactInquiriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTrialRequestsRoute: AdminTrialRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLogsRoute: typeof TeacherLogsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherScheduleRoute: typeof TeacherScheduleRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLogsRoute: TeacherLogsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherScheduleRoute: TeacherScheduleRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
